announce = false
debug = true
host = '0.0.0.0'
description = 'test'
website = 'test.com'
gamemode = 'Freeroam'
language = 'en'
modules = [ 'js-module' ]
name = 'TestServer'
players = 1024
port = 7788
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]

[js-module]
global-webcrypto = true
global-fetch = true

[voice]
bitrate = 64000

resources = [ 
    'core',
    'dbg_reconnect'
]
